//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mx.Ipn.Esime.Statistics.Core.Resources
{
    using System;
   
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages
    {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mx.Ipn.Esime.Statistics.Core.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty data set..
        /// </summary>
        public static string Empty_Data_Set
        {
            get
            {
                return ResourceManager.GetString("Empty_Data_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient data..
        /// </summary>
        public static string Insufficient_Data
        {
            get
            {
                return ResourceManager.GetString("Insufficient_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid power:{0}.
        /// </summary>
        public static string Invalid_Power_Format
        {
            get
            {
                return ResourceManager.GetString("Invalid_Power_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0}.
        /// </summary>
        public static string Invalid_Xile_Name_Format
        {
            get
            {
                return ResourceManager.GetString("Invalid_Xile_Name_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {0}.
        /// </summary>
        public static string Invalid_Xile_Name_Number_Format
        {
            get
            {
                return ResourceManager.GetString("Invalid_Xile_Name_Number_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null data Inquirer..
        /// </summary>
        public static string Null_Data_Inquirer
        {
            get
            {
                return ResourceManager.GetString("Null_Data_Inquirer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null data set..
        /// </summary>
        public static string Null_Data_Set
        {
            get
            {
                return ResourceManager.GetString("Null_Data_Set", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple_DataContainers..
        /// </summary>
        public static string Multiple_DataContainers
        {
            get
            {
                return ResourceManager.GetString("Multiple_DataContainers", resourceCulture);
            }
        }
    }
}
