//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mx.Ipn.Esime.Statistics.Core.Resources
{
    using System;
    
    
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class TaskNames
	{
        
		private static global::System.Resources.ResourceManager resourceMan;
        
		private static global::System.Globalization.CultureInfo resourceCulture;
        
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal TaskNames ()
		{
		}
        
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals (resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager ("Mx.Ipn.Esime.Statistics.Core.Resources.TaskNames", typeof(TaskNames).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
        
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to get(mad).
		/// </summary>
		public static string AbsoluteDeviation {
			get {
				return ResourceManager.GetString ("AbsoluteDeviation", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to add(F).
		/// </summary>
		public static string AcumulatedFrequencies {
			get {
				return ResourceManager.GetString ("AcumulatedFrequencies", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to add(Fr).
		/// </summary>
		public static string AcumulatedRelativeFrequencies {
			get {
				return ResourceManager.GetString ("AcumulatedRelativeFrequencies", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to add(CI).
		/// </summary>
		public static string ClassIntervals {
			get {
				return ResourceManager.GetString ("ClassIntervals", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to add(X).
		/// </summary>
		public static string ClassMarks {
			get {
				return ResourceManager.GetString ("ClassMarks", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to get(kourtosis).
		/// </summary>
		public static string CoefficientOfKourtosis {
			get {
				return ResourceManager.GetString ("CoefficientOfKourtosis", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to get(symmetry).
		/// </summary>
		public static string CoefficientOfSymmetry {
			get {
				return ResourceManager.GetString ("CoefficientOfSymmetry", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to get(cv).
		/// </summary>
		public static string CoefficientOfVariation {
			get {
				return ResourceManager.GetString ("CoefficientOfVariation", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to get(range).
		/// </summary>
		public static string DataRange {
			get {
				return ResourceManager.GetString ("DataRange", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to get(drange).
		/// </summary>
		public static string DecileRange {
			get {
				return ResourceManager.GetString ("DecileRange", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to add(f).
		/// </summary>
		public static string Frequencies {
			get {
				return ResourceManager.GetString ("Frequencies", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to add(fX).
		/// </summary>
		public static string FrequenciesTimesClassMarks {
			get {
				return ResourceManager.GetString ("FrequenciesTimesClassMarks", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to [{0},{1}].
		/// </summary>
		public static string Interval_Format {
			get {
				return ResourceManager.GetString ("Interval_Format", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to get(mean).
		/// </summary>
		public static string Mean {
			get {
				return ResourceManager.GetString ("Mean", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to fMeanDiffE{0}.
		/// </summary>
		public static string MeanDiff_Property_Format {
			get {
				return ResourceManager.GetString ("MeanDiff_Property_Format", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to add({0}).
		/// </summary>
		public static string MeanDifference_Format {
			get {
				return ResourceManager.GetString ("MeanDifference_Format", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to get(median).
		/// </summary>
		public static string Median {
			get {
				return ResourceManager.GetString ("Median", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to get(mode).
		/// </summary>
		public static string Modes {
			get {
				return ResourceManager.GetString ("Modes", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to get(momentum,{0}).
		/// </summary>
		public static string MomentumFormat {
			get {
				return ResourceManager.GetString ("MomentumFormat", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to get(prange).
		/// </summary>
		public static string PercentileRange {
			get {
				return ResourceManager.GetString ("PercentileRange", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to get(qrange).
		/// </summary>
		public static string QuartileRange {
			get {
				return ResourceManager.GetString ("QuartileRange", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to add(RI).
		/// </summary>
		public static string RealClassIntervals {
			get {
				return ResourceManager.GetString ("RealClassIntervals", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to add(fr).
		/// </summary>
		public static string RelativeFrequencies {
			get {
				return ResourceManager.GetString ("RelativeFrequencies", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to get(s).
		/// </summary>
		public static string StandarDeviation {
			get {
				return ResourceManager.GetString ("StandarDeviation", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to get(ssquare).
		/// </summary>
		public static string Variance {
			get {
				return ResourceManager.GetString ("Variance", resourceCulture);
			}
		}
        
		/// <summary>
		///   Looks up a localized string similar to get({0},{1}).
		/// </summary>
		public static string XileFormat {
			get {
				return ResourceManager.GetString ("XileFormat", resourceCulture);
			}
		}
	}
}
